# Site settings
title: Swim, bike, run, code
description: > # this means to ignore newlines until "baseurl:"
  Discoveries in building sites on Azure, swimming, biking and running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://darranshepherd.github.io" # the base hostname & protocol for your site
twitter_username: darranshepherd
github_username:  darranshepherd

# Build settings
markdown: kramdown

highlighter: pygments
